first commit
adafruit/Adafruit_Learning_System_Guides pull request #1303
Opened 2020-11-14 01:15 UTC by jedgarpark

Magtag slideshow as well as some sample images. The two illustrations are both in the public domain

2020-11-14 01:18 UTC, ladyada requested changes
we shoudl probably refactor this example to use the magtag library... do you wanna try to do that?

2020-11-14 01:29 UTC, jedgarpark commented
Sure thing, I'll give that a go @ladyada

2020-11-14 01:31 UTC, makermelissa commented
It's similar to the matrixportal library

2020-11-18 05:48 UTC, ladyada approved these changes

2020-11-18 05:48 UTC, merged