RPN Calculator: Update for CP7
adafruit/Adafruit_Learning_System_Guides pull request #1618
Opened 2021-07-19 16:01 UTC by lesamouraipourpre

Remove unused imports
Remove usage of max_size from displayio.Group
Remove usage of max_glyphs from Label

Ref: https://github.com/adafruit/Adafruit_Learning_System_Guides/issues/1603

Learn Guide:
https://learn.adafruit.com/diy-rpn-desktop-calculator-with-circuitpython/overview

Changes Needed: *nothing apparent*

2021-07-19 21:52 UTC, jepler requested changes
Thank you!  One deletion to revert, if you please.

2021-07-19 21:52 UTC, jepler commented on CircuitPython_RPN_Calculator/code.py
> -import jepler_udecimal.utrig
It's gross, but this is not actually an unused module.  Importing it causes a "side effect" of registering the trigonometric functions.

2021-07-20 15:03 UTC, jepler approved these changes
Thank you!

2021-07-20 15:03 UTC, merged

2021-07-28 20:34 UTC, TheKitty commented
Verified guide ok