fixed ulab spectrogram imports
adafruit/Adafruit_Learning_System_Guides pull request #2336
Opened 2022-11-21 19:16 UTC by evaherrada

Fixes #2335

2022-11-21 20:19 UTC, kattni requested changes
@jepler Thank you for the tag. @evaherrada Thanks for the fix! Please follow the instructions below. You should not globally disable Black, so you'll do it for each individual section.  Please apply these instructions to any obvious section I may have missed (I believe I caught them all).

2022-11-21 20:19 UTC, kattni commented on Feather_Sense_Audio_Visualizer_13x9_RGB_LED_Matrix/waterfall_visualizer/code.py
> +]
Please revert this change. Then disable Black for this section, and reenable it after the end of the section.

2022-11-21 20:19 UTC, kattni commented on Ukulele/code.py
> +    ],
Please revert this change. Then disable Black for this section, and reenable it after the end of the section.

2022-11-21 20:19 UTC, kattni commented on Ukulele/code.py
> +    ],
Please revert this change. Then disable Black for this section, and reenable it after the end of the section.

2022-11-21 20:19 UTC, kattni commented on Ukulele/code.py
> +    ],
Please revert this change. Then disable Black for this section, and reenable it after the end of the section.

2022-11-21 20:19 UTC, kattni commented on ulab_Crunch_Numbers_Fast/waterfall/code.py
> +):
Please revert this change. Then disable Black for this section, and reenable it after the end of the section.

2022-11-30 22:44 UTC, kattni commented
@evaherrada CI is failing, but I think I know why.

2022-11-30 22:45 UTC, kattni commented
@caternuson Is this the same failure that was happening previously and fixed by a PR? Does Eva simply need to pull in the changes, and let CI rerun?

2022-11-30 22:49 UTC, caternuson commented
Yep. Need to pull in the changes added with this PR:
https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2341

2022-11-30 22:50 UTC, kattni commented
@evaherrada Please check out the link Carter provided [here](https://github.com/adafruit/Adafruit_Learning_System_Guides/pull/2336#issuecomment-1332835058). You need to pull in some recent changes to make the CI pass.

2024-01-20 20:11 UTC, flavio-fernandes commented
/lgtm 
still an issue on 
```
dafruit CircuitPython 8.2.9 on 2023-12-06; Adafruit LED Glasses Driver nRF52840 with nRF52840
Board ID:adafruit_led_glasses_nrf52840
```

2024-01-20 21:30 UTC, merged