Update CircuitPython Essentials Pin Map Script for Pico W
adafruit/Adafruit_Learning_System_Guides pull request #2407
Opened 2023-02-12 17:48 UTC by anecdata

Also add a commented line to show `microcontroller` pins.

2023-03-24 14:19 UTC, dhalbert requested changes
Just a formatting change.

2023-03-24 14:19 UTC, dhalbert commented on CircuitPython_Essentials/Pin_Map_Script/code.py
> +       (cyw43 and isinstance(getattr(microcontroller.pin, pin), cyw43.CywPin)):
```suggestion
    if (isinstance(getattr(microcontroller.pin, pin), microcontroller.Pin) or 
        (cyw43 and isinstance(getattr(microcontroller.pin, pin), cyw43.CywPin))):
```

2023-03-24 14:48 UTC, dhalbert requested changes

2023-03-24 14:48 UTC, dhalbert commented on CircuitPython_Essentials/Pin_Map_Script/code.py
> +    if (isinstance(getattr(microcontroller.pin, pin), microcontroller.Pin) or
```suggestion
    if (isinstance(getattr(microcontroller.pin, pin), microcontroller.Pin) or
```

2023-03-29 05:37 UTC, anecdata commented
Is there more to do here? Dan made the changes and it's better now. Change requests appear to be resolved, but Github still doesn't look happy.

2023-09-21 15:37 UTC, anecdata commented
fixed conflict, and removed commented-out lines to show microcontroller pins since that was redundant with the added lies to show original GPIO parenthetically

(history of this little code snippet, as close as I could reconstruct it, is [here](https://gist.github.com/anecdata/1c345cb2d137776d76b97a5d5678dc97))

2023-09-21 15:46 UTC, dhalbert approved these changes
Looks good - thanks!

2023-09-21 15:47 UTC, merged